# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
jdk:
  # JDK 8 is set to deploy the docs and artifacts
  - oraclejdk8
env:
  - SERVER=jetty DATABASE=h2 DEPLOY_DOCS=true
  - SERVER=tomcat7 DATABASE=h2
dist: precise

before_install:
  # Gets scripts
  - git clone -b v1.0.0 --single-branch https://github.com/Bernardo-MG/ci-shell-scripts.git ~/.scripts
  # Sets scripts as executable
  - chmod -R +x ~/.scripts/*
  # Prepares CI environment
  - source ~/.scripts/travis/load-travis-environment.sh
before_script:
  # Creates Maven settings
  - ~/.scripts/java/maven/create-maven-settings.sh $VERSION_TYPE
  # Creates test databases
  - ./.scripts/create-test-databases.sh
script:
  # Unit and integration tests are run
  - mvn clean verify -P $DATABASE,$SERVER
after_success:
  # Documentation deployment script
  - ~/.scripts/java/maven/deploy-site.sh $DO_DEPLOY_DOCS deployment,$SERVER
